### ISSUE TITLE
Docs request: Implementation of EndpointInterface::__invoke

### ISSUE THREAD

**Issue by sorenmalling** [flownative/flow-graphql#1]
The README example uses the `excuteQuery` implementation of EndpointInterface.

The `excuteQuery` method was replaced by `__invoke` in latest commit, but has a different signature.

Could it be, that the README example can be updated with and example of the `__invoke` method

**Comment by kdambekalns** [comment]
Example needs to be adjusted to https://github.com/flownative/flow-graphql/commit/57ee3f32b2123f782c61521f0e1625a619573df7
